### ISSUE TITLE
Cart totals inaccurate for coupon discounts that apply to each cart item

### ISSUE THREAD

**Issue by Mopok** [lemonstand/lscloud-theme-coffree#36]
![screen shot 2017-03-21 at 11 54 03 am](https://cloud.githubusercontent.com/assets/14959054/24165233/1a590590-0e2d-11e7-97e1-a67f504e6fdf.png)
![screen shot 2017-03-21 at 11 54 20 am](https://cloud.githubusercontent.com/assets/14959054/24165250/22d17626-0e2d-11e7-9b0e-b6d00f09631f.png)

First screen shot shows that the discount to each cart item is only added to total discount once, not once for each cart item. The second screen shot shows the coupon set up to do this.

This is only a problem for multiple items in the cart.

**Comment by tomcornall** [comment]
Fixed in https://github.com/lemonstand/lemonstand-2/pull/4113
